# Upload Assistant © 2025 Audionut & wastaken7 — Licensed under UAPL v1.0
import re
from typing import Any, Callable, Optional, Union, cast

import guessit

guessit_module: Any = cast(Any, guessit)
GuessitFn = Callable[[str, Optional[dict[str, Any]]], dict[str, Any]]


def guessit_fn(value: str, options: Optional[dict[str, Any]] = None) -> dict[str, Any]:
    return cast(dict[str, Any], guessit_module.guessit(value, options))


async def get_region(bdinfo: dict[str, Any], region: Optional[str] = None) -> str:
    label = bdinfo.get("label", bdinfo.get("title", bdinfo.get("path", ""))).replace(".", " ")
    if region is not None:
        region = region.upper()
    else:
        regions = {
            "AFG": "AFG",
            "AIA": "AIA",
            "ALA": "ALA",
            "ALG": "ALG",
            "AND": "AND",
            "ANG": "ANG",
            "ARG": "ARG",
            "ARM": "ARM",
            "ARU": "ARU",
            "ASA": "ASA",
            "ATA": "ATA",
            "ATF": "ATF",
            "ATG": "ATG",
            "AUS": "AUS",
            "AUT": "AUT",
            "AZE": "AZE",
            "BAH": "BAH",
            "BAN": "BAN",
            "BDI": "BDI",
            "BEL": "BEL",
            "BEN": "BEN",
            "BER": "BER",
            "BES": "BES",
            "BFA": "BFA",
            "BHR": "BHR",
            "BHU": "BHU",
            "BIH": "BIH",
            "BLM": "BLM",
            "BLR": "BLR",
            "BLZ": "BLZ",
            "BOL": "BOL",
            "BOT": "BOT",
            "BRA": "BRA",
            "BRB": "BRB",
            "BRU": "BRU",
            "BVT": "BVT",
            "CAM": "CAM",
            "CAN": "CAN",
            "CAY": "CAY",
            "CCK": "CCK",
            "CEE": "CEE",
            "CGO": "CGO",
            "CHA": "CHA",
            "CHI": "CHI",
            "CHN": "CHN",
            "CIV": "CIV",
            "CMR": "CMR",
            "COD": "COD",
            "COK": "COK",
            "COL": "COL",
            "COM": "COM",
            "CPV": "CPV",
            "CRC": "CRC",
            "CRO": "CRO",
            "CTA": "CTA",
            "CUB": "CUB",
            "CUW": "CUW",
            "CXR": "CXR",
            "CYP": "CYP",
            "DJI": "DJI",
            "DMA": "DMA",
            "DOM": "DOM",
            "ECU": "ECU",
            "EGY": "EGY",
            "ENG": "ENG",
            "EQG": "EQG",
            "ERI": "ERI",
            "ESH": "ESH",
            "ESP": "ESP",
            "ETH": "ETH",
            "FIJ": "FIJ",
            "FLK": "FLK",
            "FRA": "FRA",
            "FRO": "FRO",
            "FSM": "FSM",
            "GAB": "GAB",
            "GAM": "GAM",
            "GBR": "GBR",
            "GEO": "GEO",
            "GER": "GER",
            "GGY": "GGY",
            "GHA": "GHA",
            "GIB": "GIB",
            "GLP": "GLP",
            "GNB": "GNB",
            "GRE": "GRE",
            "GRL": "GRL",
            "GRN": "GRN",
            "GUA": "GUA",
            "GUF": "GUF",
            "GUI": "GUI",
            "GUM": "GUM",
            "GUY": "GUY",
            "HAI": "HAI",
            "HKG": "HKG",
            "HMD": "HMD",
            "HON": "HON",
            "HUN": "HUN",
            "IDN": "IDN",
            "IMN": "IMN",
            "IND": "IND",
            "IOT": "IOT",
            "IRL": "IRL",
            "IRN": "IRN",
            "IRQ": "IRQ",
            "ISL": "ISL",
            "ISR": "ISR",
            "ITA": "ITA",
            "JAM": "JAM",
            "JEY": "JEY",
            "JOR": "JOR",
            "JPN": "JPN",
            "KAZ": "KAZ",
            "KEN": "KEN",
            "KGZ": "KGZ",
            "KIR": "KIR",
            "KNA": "KNA",
            "KOR": "KOR",
            "KSA": "KSA",
            "KUW": "KUW",
            "KVX": "KVX",
            "LAO": "LAO",
            "LBN": "LBN",
            "LBR": "LBR",
            "LBY": "LBY",
            "LCA": "LCA",
            "LES": "LES",
            "LIE": "LIE",
            "LKA": "LKA",
            "LUX": "LUX",
            "MAC": "MAC",
            "MAD": "MAD",
            "MAF": "MAF",
            "MAR": "MAR",
            "MAS": "MAS",
            "MDA": "MDA",
            "MDV": "MDV",
            "MEX": "MEX",
            "MHL": "MHL",
            "MKD": "MKD",
            "MLI": "MLI",
            "MLT": "MLT",
            "MNG": "MNG",
            "MNP": "MNP",
            "MON": "MON",
            "MOZ": "MOZ",
            "MRI": "MRI",
            "MSR": "MSR",
            "MTN": "MTN",
            "MTQ": "MTQ",
            "MWI": "MWI",
            "MYA": "MYA",
            "MYT": "MYT",
            "NAM": "NAM",
            "NCA": "NCA",
            "NCL": "NCL",
            "NEP": "NEP",
            "NFK": "NFK",
            "NIG": "NIG",
            "NIR": "NIR",
            "NIU": "NIU",
            "NLD": "NLD",
            "NOR": "NOR",
            "NRU": "NRU",
            "NZL": "NZL",
            "OMA": "OMA",
            "PAK": "PAK",
            "PAN": "PAN",
            "PAR": "PAR",
            "PCN": "PCN",
            "PER": "PER",
            "PHI": "PHI",
            "PLE": "PLE",
            "PLW": "PLW",
            "PNG": "PNG",
            "POL": "POL",
            "POR": "POR",
            "PRK": "PRK",
            "PUR": "PUR",
            "QAT": "QAT",
            "REU": "REU",
            "ROU": "ROU",
            "RSA": "RSA",
            "RUS": "RUS",
            "RWA": "RWA",
            "SAM": "SAM",
            "SCO": "SCO",
            "SDN": "SDN",
            "SEN": "SEN",
            "SEY": "SEY",
            "SGS": "SGS",
            "SHN": "SHN",
            "SIN": "SIN",
            "SJM": "SJM",
            "SLE": "SLE",
            "SLV": "SLV",
            "SMR": "SMR",
            "SOL": "SOL",
            "SOM": "SOM",
            "SPM": "SPM",
            "SRB": "SRB",
            "SSD": "SSD",
            "STP": "STP",
            "SUI": "SUI",
            "SUR": "SUR",
            "SWZ": "SWZ",
            "SXM": "SXM",
            "SYR": "SYR",
            "TAH": "TAH",
            "TAN": "TAN",
            "TCA": "TCA",
            "TGA": "TGA",
            "THA": "THA",
            "TJK": "TJK",
            "TKL": "TKL",
            "TKM": "TKM",
            "TLS": "TLS",
            "TOG": "TOG",
            "TRI": "TRI",
            "TUN": "TUN",
            "TUR": "TUR",
            "TUV": "TUV",
            "TWN": "TWN",
            "UAE": "UAE",
            "UGA": "UGA",
            "UKR": "UKR",
            "UMI": "UMI",
            "URU": "URU",
            "USA": "USA",
            "UZB": "UZB",
            "VAN": "VAN",
            "VAT": "VAT",
            "VEN": "VEN",
            "VGB": "VGB",
            "VIE": "VIE",
            "VIN": "VIN",
            "VIR": "VIR",
            "WAL": "WAL",
            "WLF": "WLF",
            "YEM": "YEM",
            "ZAM": "ZAM",
            "ZIM": "ZIM",
            "EUR": "EUR",
        }
        for key, value in regions.items():
            if f" {key} " in label:
                region = value

    if region is None:
        region = ""
    return region


async def get_distributor(distributor_in: Optional[str]) -> str:
    distributor_list = [
        "01 DISTRIBUTION",
        "100 DESTINATIONS TRAVEL FILM",
        "101 FILMS",
        "1FILMS",
        "2 ENTERTAIN VIDEO",
        "20TH CENTURY FOX",
        "2L",
        "3D CONTENT HUB",
        "3D MEDIA",
        "3L FILM",
        "4DIGITAL",
        "4DVD",
        "4K ULTRA HD MOVIES",
        "4K UHD",
        "8-FILMS",
        "84 ENTERTAINMENT",
        "88 FILMS",
        "@ANIME",
        "ANIME",
        "A CONTRACORRIENTE",
        "A CONTRACORRIENTE FILMS",
        "A&E HOME VIDEO",
        "A&E",
        "A&M RECORDS",
        "A+E NETWORKS",
        "A+R",
        "A-FILM",
        "AAA",
        "AB VIDÉO",
        "AB VIDEO",
        "ABC - (AUSTRALIAN BROADCASTING CORPORATION)",
        "ABC",
        "ABKCO",
        "ABSOLUT MEDIEN",
        "ABSOLUTE",
        "ACCENT FILM ENTERTAINMENT",
        "ACCENTUS",
        "ACORN MEDIA",
        "AD VITAM",
        "ADA",
        "ADITYA VIDEOS",
        "ADSO FILMS",
        "AFM RECORDS",
        "AGFA",
        "AIX RECORDS",
        "ALAMODE FILM",
        "ALBA RECORDS",
        "ALBANY RECORDS",
        "ALBATROS",
        "ALCHEMY",
        "ALIVE",
        "ALL ANIME",
        "ALL INTERACTIVE ENTERTAINMENT",
        "ALLEGRO",
        "ALLIANCE",
        "ALPHA MUSIC",
        "ALTERDYSTRYBUCJA",
        "ALTERED INNOCENCE",
        "ALTITUDE FILM DISTRIBUTION",
        "ALUCARD RECORDS",
        "AMAZING D.C.",
        "AMAZING DC",
        "AMMO CONTENT",
        "AMUSE SOFT ENTERTAINMENT",
        "ANCONNECT",
        "ANEC",
        "ANIMATSU",
        "ANIME HOUSE",
        "ANIME LTD",
        "ANIME WORKS",
        "ANIMEIGO",
        "ANIPLEX",
        "ANOLIS ENTERTAINMENT",
        "ANOTHER WORLD ENTERTAINMENT",
        "AP INTERNATIONAL",
        "APPLE",
        "ARA MEDIA",
        "ARBELOS",
        "ARC ENTERTAINMENT",
        "ARP SÉLECTION",
        "ARP SELECTION",
        "ARROW",
        "ART SERVICE",
        "ART VISION",
        "ARTE ÉDITIONS",
        "ARTE EDITIONS",
        "ARTE VIDÉO",
        "ARTE VIDEO",
        "ARTHAUS MUSIK",
        "ARTIFICIAL EYE",
        "ARTSPLOITATION FILMS",
        "ARTUS FILMS",
        "ASCOT ELITE HOME ENTERTAINMENT",
        "ASIA VIDEO",
        "ASMIK ACE",
        "ASTRO RECORDS & FILMWORKS",
        "ASYLUM",
        "ATLANTIC FILM",
        "ATLANTIC RECORDS",
        "ATLAS FILM",
        "AUDIO VISUAL ENTERTAINMENT",
        "AURO-3D CREATIVE LABEL",
        "AURUM",
        "AV VISIONEN",
        "AV-JET",
        "AVALON",
        "AVENTI",
        "AVEX TRAX",
        "AXIOM",
        "AXIS RECORDS",
        "AYNGARAN",
        "BAC FILMS",
        "BACH FILMS",
        "BANDAI VISUAL",
        "BARCLAY",
        "BBC",
        "BRITISH BROADCASTING CORPORATION",
        "BBI FILMS",
        "BBI",
        "BCI HOME ENTERTAINMENT",
        "BEGGARS BANQUET",
        "BEL AIR CLASSIQUES",
        "BELGA FILMS",
        "BELVEDERE",
        "BENELUX FILM DISTRIBUTORS",
        "BENNETT-WATT MEDIA",
        "BERLIN CLASSICS",
        "BERLINER PHILHARMONIKER RECORDINGS",
        "BEST ENTERTAINMENT",
        "BEYOND HOME ENTERTAINMENT",
        "BFI VIDEO",
        "BFI",
        "BRITISH FILM INSTITUTE",
        "BFS ENTERTAINMENT",
        "BFS",
        "BHAVANI",
        "BIBER RECORDS",
        "BIG HOME VIDEO",
        "BILDSTÖRUNG",
        "BILDSTORUNG",
        "BILL ZEBUB",
        "BIRNENBLATT",
        "BIT WEL",
        "BLACK BOX",
        "BLACK HILL PICTURES",
        "BLACK HILL",
        "BLACK HOLE RECORDINGS",
        "BLACK HOLE",
        "BLAQOUT",
        "BLAUFIELD MUSIC",
        "BLAUFIELD",
        "BLOCKBUSTER ENTERTAINMENT",
        "BLOCKBUSTER",
        "BLU PHASE MEDIA",
        "BLU-RAY ONLY",
        "BLU-RAY",
        "BLURAY ONLY",
        "BLURAY",
        "BLUE GENTIAN RECORDS",
        "BLUE KINO",
        "BLUE UNDERGROUND",
        "BMG/ARISTA",
        "BMG",
        "BMGARISTA",
        "BMG ARISTA",
        "ARISTA",
        "ARISTA/BMG",
        "ARISTABMG",
        "ARISTA BMG",
        "BONTON FILM",
        "BONTON",
        "BOOMERANG PICTURES",
        "BOOMERANG",
        "BQHL ÉDITIONS",
        "BQHL EDITIONS",
        "BQHL",
        "BREAKING GLASS",
        "BRIDGESTONE",
        "BRINK",
        "BROAD GREEN PICTURES",
        "BROAD GREEN",
        "BUSCH MEDIA GROUP",
        "BUSCH",
        "C MAJOR",
        "C.B.S.",
        "CAICHANG",
        "CALIFÓRNIA FILMES",
        "CALIFORNIA FILMES",
        "CALIFORNIA",
        "CAMEO",
        "CAMERA OBSCURA",
        "CAMERATA",
        "CAMP MOTION PICTURES",
        "CAMP MOTION",
        "CAPELIGHT PICTURES",
        "CAPELIGHT",
        "CAPITOL",
        "CAPITOL RECORDS",
        "CAPRICCI",
        "CARGO RECORDS",
        "CARLOTTA FILMS",
        "CARLOTTA",
        "CARLOTA",
        "CARMEN FILM",
        "CASCADE",
        "CATCHPLAY",
        "CAULDRON FILMS",
        "CAULDRON",
        "CBS TELEVISION STUDIOS",
        "CBS",
        "CCTV",
        "CCV ENTERTAINMENT",
        "CCV",
        "CD BABY",
        "CD LAND",
        "CECCHI GORI",
        "CENTURY MEDIA",
        "CHUAN XUN SHI DAI MULTIMEDIA",
        "CINE-ASIA",
        "CINÉART",
        "CINEART",
        "CINEDIGM",
        "CINEFIL IMAGICA",
        "CINEMA EPOCH",
        "CINEMA GUILD",
        "CINEMA LIBRE STUDIOS",
        "CINEMA MONDO",
        "CINEMATIC VISION",
        "CINEPLOIT RECORDS",
        "CINESTRANGE EXTREME",
        "CITEL VIDEO",
        "CITEL",
        "CJ ENTERTAINMENT",
        "CJ",
        "CLASSIC MEDIA",
        "CLASSICFLIX",
        "CLASSICLINE",
        "CLAUDIO RECORDS",
        "CLEAR VISION",
        "CLEOPATRA",
        "CLOSE UP",
        "CMS MEDIA LIMITED",
        "CMV LASERVISION",
        "CN ENTERTAINMENT",
        "CODE RED",
        "COHEN MEDIA GROUP",
        "COHEN",
        "COIN DE MIRE CINÉMA",
        "COIN DE MIRE CINEMA",
        "COLOSSEO FILM",
        "COLUMBIA",
        "COLUMBIA PICTURES",
        "COLUMBIA/TRI-STAR",
        "TRI-STAR",
        "COMMERCIAL MARKETING",
        "CONCORD MUSIC GROUP",
        "CONCORDE VIDEO",
        "CONDOR",
        "CONSTANTIN FILM",
        "CONSTANTIN",
        "CONSTANTINO FILMES",
        "CONSTANTINO",
        "CONSTRUCTIVE MEDIA SERVICE",
        "CONSTRUCTIVE",
        "CONTENT ZONE",
        "CONTENTS GATE",
        "COQUEIRO VERDE",
        "CORNERSTONE MEDIA",
        "CORNERSTONE",
        "CP DIGITAL",
        "CREST MOVIES",
        "CRITERION",
        "CRITERION COLLECTION",
        "CC",
        "CRYSTAL CLASSICS",
        "CULT EPICS",
        "CULT FILMS",
        "CULT VIDEO",
        "CURZON FILM WORLD",
        "D FILMS",
        "D'AILLY COMPANY",
        "DAILLY COMPANY",
        "D AILLY COMPANY",
        "D'AILLY",
        "DAILLY",
        "D AILLY",
        "DA CAPO",
        "DA MUSIC",
        "DALL'ANGELO PICTURES",
        "DALLANGELO PICTURES",
        "DALL'ANGELO",
        "DALL ANGELO PICTURES",
        "DALL ANGELO",
        "DAREDO",
        "DARK FORCE ENTERTAINMENT",
        "DARK FORCE",
        "DARK SIDE RELEASING",
        "DARK SIDE",
        "DAZZLER MEDIA",
        "DAZZLER",
        "DCM PICTURES",
        "DCM",
        "DEAPLANETA",
        "DECCA",
        "DEEPJOY",
        "DEFIANT SCREEN ENTERTAINMENT",
        "DEFIANT SCREEN",
        "DEFIANT",
        "DELOS",
        "DELPHIAN RECORDS",
        "DELPHIAN",
        "DELTA MUSIC & ENTERTAINMENT",
        "DELTA MUSIC AND ENTERTAINMENT",
        "DELTA MUSIC ENTERTAINMENT",
        "DELTA MUSIC",
        "DELTAMAC CO. LTD.",
        "DELTAMAC CO LTD",
        "DELTAMAC CO",
        "DELTAMAC",
        "DEMAND MEDIA",
        "DEMAND",
        "DEP",
        "DEUTSCHE GRAMMOPHON",
        "DFW",
        "DGM",
        "DIAPHANA",
        "DIGIDREAMS STUDIOS",
        "DIGIDREAMS",
        "DIGITAL ENVIRONMENTS",
        "DIGITAL",
        "DISCOTEK MEDIA",
        "DISCOVERY CHANNEL",
        "DISCOVERY",
        "DISK KINO",
        "DISNEY / BUENA VISTA",
        "DISNEY",
        "BUENA VISTA",
        "DISNEY BUENA VISTA",
        "DISTRIBUTION SELECT",
        "DIVISA",
        "DNC ENTERTAINMENT",
        "DNC",
        "DOGWOOF",
        "DOLMEN HOME VIDEO",
        "DOLMEN",
        "DONAU FILM",
        "DONAU",
        "DORADO FILMS",
        "DORADO",
        "DRAFTHOUSE FILMS",
        "DRAFTHOUSE",
        "DRAGON FILM ENTERTAINMENT",
        "DRAGON ENTERTAINMENT",
        "DRAGON FILM",
        "DRAGON",
        "DREAMWORKS",
        "DRIVE ON RECORDS",
        "DRIVE ON",
        "DRIVE-ON",
        "DRIVEON",
        "DS MEDIA",
        "DTP ENTERTAINMENT AG",
        "DTP ENTERTAINMENT",
        "DTP AG",
        "DTP",
        "DTS ENTERTAINMENT",
        "DTS",
        "DUKE MARKETING",
        "DUKE VIDEO DISTRIBUTION",
        "DUKE",
        "DUTCH FILMWORKS",
        "DUTCH",
        "DVD INTERNATIONAL",
        "DVD",
        "DYBEX",
        "DYNAMIC",
        "DYNIT",
        "E1 ENTERTAINMENT",
        "E1",
        "EAGLE ENTERTAINMENT",
        "EAGLE HOME ENTERTAINMENT PVT.LTD.",
        "EAGLE HOME ENTERTAINMENT PVTLTD",
        "EAGLE HOME ENTERTAINMENT PVT LTD",
        "EAGLE HOME ENTERTAINMENT",
        "EAGLE PICTURES",
        "EAGLE ROCK ENTERTAINMENT",
        "EAGLE ROCK",
        "EAGLE VISION MEDIA",
        "EAGLE VISION",
        "EARMUSIC",
        "EARTH ENTERTAINMENT",
        "EARTH",
        "ECHO BRIDGE ENTERTAINMENT",
        "ECHO BRIDGE",
        "EDEL GERMANY GMBH",
        "EDEL GERMANY",
        "EDEL RECORDS",
        "EDITION TONFILM",
        "EDITIONS MONTPARNASSE",
        "EDKO FILMS LTD.",
        "EDKO FILMS LTD",
        "EDKO FILMS",
        "EDKO",
        "EIN'S M&M CO",
        "EINS M&M CO",
        "EIN'S M&M",
        "EINS M&M",
        "ELEA-MEDIA",
        "ELEA MEDIA",
        "ELEA",
        "ELECTRIC PICTURE",
        "ELECTRIC",
        "ELEPHANT FILMS",
        "ELEPHANT",
        "ELEVATION",
        "EMI",
        "EMON",
        "EMS",
        "EMYLIA",
        "ENE MEDIA",
        "ENE",
        "ENTERTAINMENT IN VIDEO",
        "ENTERTAINMENT IN",
        "ENTERTAINMENT ONE",
        "ENTERTAINMENT ONE FILMS CANADA INC.",
        "ENTERTAINMENT ONE FILMS CANADA INC",
        "ENTERTAINMENT ONE FILMS CANADA",
        "ENTERTAINMENT ONE CANADA INC",
        "ENTERTAINMENT ONE CANADA",
        "ENTERTAINMENTONE",
        "EONE",
        "EOS",
        "EPIC PICTURES",
        "EPIC",
        "EPIC RECORDS",
        "ERATO",
        "EROS",
        "ESC EDITIONS",
        "ESCAPI MEDIA BV",
        "ESOTERIC RECORDINGS",
        "ESPN FILMS",
        "EUREKA ENTERTAINMENT",
        "EUREKA",
        "EURO PICTURES",
        "EURO VIDEO",
        "EUROARTS",
        "EUROPA FILMES",
        "EUROPA",
        "EUROPACORP",
        "EUROZOOM",
        "EXCEL",
        "EXPLOSIVE MEDIA",
        "EXPLOSIVE",
        "EXTRALUCID FILMS",
        "EXTRALUCID",
        "EYE SEE MOVIES",
        "EYE SEE",
        "EYK MEDIA",
        "EYK",
        "FABULOUS FILMS",
        "FABULOUS",
        "FACTORIS FILMS",
        "FACTORIS",
        "FARAO RECORDS",
        "FARBFILM HOME ENTERTAINMENT",
        "FARBFILM ENTERTAINMENT",
        "FARBFILM HOME",
        "FARBFILM",
        "FEELGOOD ENTERTAINMENT",
        "FEELGOOD",
        "FERNSEHJUWELEN",
        "FILM CHEST",
        "FILM MEDIA",
        "FILM MOVEMENT",
        "FILM4",
        "FILMART",
        "FILMAURO",
        "FILMAX",
        "FILMCONFECT HOME ENTERTAINMENT",
        "FILMCONFECT ENTERTAINMENT",
        "FILMCONFECT HOME",
        "FILMCONFECT",
        "FILMEDIA",
        "FILMJUWELEN",
        "FILMOTEKA NARODAWA",
        "FILMRISE",
        "FINAL CUT ENTERTAINMENT",
        "FINAL CUT",
        "FIREHOUSE 12 RECORDS",
        "FIREHOUSE 12",
        "FIRST INTERNATIONAL PRODUCTION",
        "FIRST INTERNATIONAL",
        "FIRST LOOK STUDIOS",
        "FIRST LOOK",
        "FLAGMAN TRADE",
        "FLASHSTAR FILMES",
        "FLASHSTAR",
        "FLICKER ALLEY",
        "FNC ADD CULTURE",
        "FOCUS FILMES",
        "FOCUS",
        "FOKUS MEDIA",
        "FOKUSA",
        "FOX PATHE EUROPA",
        "FOX PATHE",
        "FOX EUROPA",
        "FOX/MGM",
        "FOX MGM",
        "MGM",
        "MGM/FOX",
        "FOX",
        "FPE",
        "FRANCE TÉLÉVISIONS DISTRIBUTION",
        "FRANCE TELEVISIONS DISTRIBUTION",
        "FRANCE TELEVISIONS",
        "FRANCE",
        "FREE DOLPHIN ENTERTAINMENT",
        "FREE DOLPHIN",
        "FREESTYLE DIGITAL MEDIA",
        "FREESTYLE DIGITAL",
        "FREESTYLE",
        "FREMANTLE HOME ENTERTAINMENT",
        "FREMANTLE ENTERTAINMENT",
        "FREMANTLE HOME",
        "FREMANTL",
        "FRENETIC FILMS",
        "FRENETIC",
        "FRONTIER WORKS",
        "FRONTIER",
        "FRONTIERS MUSIC",
        "FRONTIERS RECORDS",
        "FS FILM OY",
        "FS FILM",
        "FULL MOON FEATURES",
        "FULL MOON",
        "FUN CITY EDITIONS",
        "FUN CITY",
        "FUNIMATION ENTERTAINMENT",
        "FUNIMATION",
        "FUSION",
        "FUTUREFILM",
        "G2 PICTURES",
        "G2",
        "GAGA COMMUNICATIONS",
        "GAGA",
        "GAIAM",
        "GALAPAGOS",
        "GAMMA HOME ENTERTAINMENT",
        "GAMMA ENTERTAINMENT",
        "GAMMA HOME",
        "GAMMA",
        "GARAGEHOUSE PICTURES",
        "GARAGEHOUSE",
        "GARAGEPLAY (車庫娛樂)",
        "車庫娛樂",
        "GARAGEPLAY (Che Ku Yu Le )",
        "GARAGEPLAY",
        "Che Ku Yu Le",
        "GAUMONT",
        "GEFFEN",
        "GENEON ENTERTAINMENT",
        "GENEON",
        "GENEON UNIVERSAL ENTERTAINMENT",
        "GENERAL VIDEO RECORDING",
        "GLASS DOLL FILMS",
        "GLASS DOLL",
        "GLOBE MUSIC MEDIA",
        "GLOBE MUSIC",
        "GLOBE MEDIA",
        "GLOBE",
        "GO ENTERTAIN",
        "GO",
        "GOLDEN HARVEST",
        "GOOD!MOVIES",
        "GOOD! MOVIES",
        "GOOD MOVIES",
        "GRAPEVINE VIDEO",
        "GRAPEVINE",
        "GRASSHOPPER FILM",
        "GRASSHOPPER FILMS",
        "GRASSHOPPER",
        "GRAVITAS VENTURES",
        "GRAVITAS",
        "GREAT MOVIES",
        "GREAT",
        "GREEN APPLE ENTERTAINMENT",
        "GREEN ENTERTAINMENT",
        "GREEN APPLE",
        "GREEN",
        "GREENNARAE MEDIA",
        "GREENNARAE",
        "GRINDHOUSE RELEASING",
        "GRINDHOUSE",
        "GRIND HOUSE",
        "GRYPHON ENTERTAINMENT",
        "GRYPHON",
        "GUNPOWDER & SKY",
        "GUNPOWDER AND SKY",
        "GUNPOWDER SKY",
        "GUNPOWDER + SKY",
        "GUNPOWDER",
        "HANABEE ENTERTAINMENT",
        "HANABEE",
        "HANNOVER HOUSE",
        "HANNOVER",
        "HANSESOUND",
        "HANSE SOUND",
        "HANSE",
        "HAPPINET",
        "HARMONIA MUNDI",
        "HARMONIA",
        "HBO",
        "HDC",
        "HEC",
        "HELL & BACK RECORDINGS",
        "HELL AND BACK RECORDINGS",
        "HELL & BACK",
        "HELL AND BACK",
        "HEN'S TOOTH VIDEO",
        "HENS TOOTH VIDEO",
        "HEN'S TOOTH",
        "HENS TOOTH",
        "HIGH FLIERS",
        "HIGHLIGHT",
        "HILLSONG",
        "HISTORY CHANNEL",
        "HISTORY",
        "HK VIDÉO",
        "HK VIDEO",
        "HK",
        "HMH HAMBURGER MEDIEN HAUS",
        "HAMBURGER MEDIEN HAUS",
        "HMH HAMBURGER MEDIEN",
        "HMH HAMBURGER",
        "HMH",
        "HOLLYWOOD CLASSIC ENTERTAINMENT",
        "HOLLYWOOD CLASSIC",
        "HOLLYWOOD PICTURES",
        "HOLLYWOOD",
        "HOPSCOTCH ENTERTAINMENT",
        "HOPSCOTCH",
        "HPM",
        "HÄNNSLER CLASSIC",
        "HANNSLER CLASSIC",
        "HANNSLER",
        "I-CATCHER",
        "I CATCHER",
        "ICATCHER",
        "I-ON NEW MEDIA",
        "I ON NEW MEDIA",
        "ION NEW MEDIA",
        "ION MEDIA",
        "I-ON",
        "ION",
        "IAN PRODUCTIONS",
        "IAN",
        "ICESTORM",
        "ICON FILM DISTRIBUTION",
        "ICON DISTRIBUTION",
        "ICON FILM",
        "ICON",
        "IDEALE AUDIENCE",
        "IDEALE",
        "IFC FILMS",
        "IFC",
        "IFILM",
        "ILLUSIONS UNLTD.",
        "ILLUSIONS UNLTD",
        "ILLUSIONS",
        "IMAGE ENTERTAINMENT",
        "IMAGE",
        "IMAGEM FILMES",
        "IMAGEM",
        "IMOVISION",
        "IMPERIAL CINEPIX",
        "IMPRINT",
        "IMPULS HOME ENTERTAINMENT",
        "IMPULS ENTERTAINMENT",
        "IMPULS HOME",
        "IMPULS",
        "IN-AKUSTIK",
        "IN AKUSTIK",
        "INAKUSTIK",
        "INCEPTION MEDIA GROUP",
        "INCEPTION MEDIA",
        "INCEPTION GROUP",
        "INCEPTION",
        "INDEPENDENT",
        "INDICAN",
        "INDIE RIGHTS",
        "INDIE",
        "INDIGO",
        "INFO",
        "INJOINGAN",
        "INKED PICTURES",
        "INKED",
        "INSIDE OUT MUSIC",
        "INSIDE MUSIC",
        "INSIDE OUT",
        "INSIDE",
        "INTERCOM",
        "INTERCONTINENTAL VIDEO",
        "INTERCONTINENTAL",
        "INTERGROOVE",
        "INTERSCOPE",
        "INVINCIBLE PICTURES",
        "INVINCIBLE",
        "ISLAND/MERCURY",
        "ISLAND MERCURY",
        "ISLANDMERCURY",
        "ISLAND & MERCURY",
        "ISLAND AND MERCURY",
        "ISLAND",
        "ITN",
        "ITV DVD",
        "ITV",
        "IVC",
        "IVE ENTERTAINMENT",
        "IVE",
        "J&R ADVENTURES",
        "J&R",
        "JR",
        "JAKOB",
        "JONU MEDIA",
        "JONU",
        "JRB PRODUCTIONS",
        "JRB",
        "JUST BRIDGE ENTERTAINMENT",
        "JUST BRIDGE",
        "JUST ENTERTAINMENT",
        "JUST",
        "KABOOM ENTERTAINMENT",
        "KABOOM",
        "KADOKAWA ENTERTAINMENT",
        "KADOKAWA",
        "KAIROS",
        "KALEIDOSCOPE ENTERTAINMENT",
        "KALEIDOSCOPE",
        "KAM & RONSON ENTERPRISES",
        "KAM & RONSON",
        "KAM&RONSON ENTERPRISES",
        "KAM&RONSON",
        "KAM AND RONSON ENTERPRISES",
        "KAM AND RONSON",
        "KANA HOME VIDEO",
        "KARMA FILMS",
        "KARMA",
        "KATZENBERGER",
        "KAZE",
        "KBS MEDIA",
        "KBS",
        "KD MEDIA",
        "KD",
        "KING MEDIA",
        "KING",
        "KING RECORDS",
        "KINO LORBER",
        "KINO",
        "KINO SWIAT",
        "KINOKUNIYA",
        "KINOWELT HOME ENTERTAINMENT/DVD",
        "KINOWELT HOME ENTERTAINMENT",
        "KINOWELT ENTERTAINMENT",
        "KINOWELT HOME DVD",
        "KINOWELT ENTERTAINMENT/DVD",
        "KINOWELT DVD",
        "KINOWELT",
        "KIT PARKER FILMS",
        "KIT PARKER",
        "KITTY MEDIA",
        "KNM HOME ENTERTAINMENT",
        "KNM ENTERTAINMENT",
        "KNM HOME",
        "KNM",
        "KOBA FILMS",
        "KOBA",
        "KOCH ENTERTAINMENT",
        "KOCH MEDIA",
        "KOCH",
        "KRAKEN RELEASING",
        "KRAKEN",
        "KSCOPE",
        "KSM",
        "KULTUR",
        "L'ATELIER D'IMAGES",
        "LATELIER D'IMAGES",
        "L'ATELIER DIMAGES",
        "LATELIER DIMAGES",
        "L ATELIER D'IMAGES",
        "L'ATELIER D IMAGES",
        "L ATELIER D IMAGES",
        "L'ATELIER",
        "L ATELIER",
        "LATELIER",
        "LA AVENTURA AUDIOVISUAL",
        "LA AVENTURA",
        "LACE GROUP",
        "LACE",
        "LASER PARADISE",
        "LAYONS",
        "LCJ EDITIONS",
        "LCJ",
        "LE CHAT QUI FUME",
        "LE PACTE",
        "LEDICK FILMHANDEL",
        "LEGEND",
        "LEOMARK STUDIOS",
        "LEOMARK",
        "LEONINE FILMS",
        "LEONINE",
        "LICHTUNG MEDIA LTD",
        "LICHTUNG LTD",
        "LICHTUNG MEDIA LTD.",
        "LICHTUNG LTD.",
        "LICHTUNG MEDIA",
        "LICHTUNG",
        "LIGHTHOUSE HOME ENTERTAINMENT",
        "LIGHTHOUSE ENTERTAINMENT",
        "LIGHTHOUSE HOME",
        "LIGHTHOUSE",
        "LIGHTYEAR",
        "LIONSGATE FILMS",
        "LIONSGATE",
        "LIZARD CINEMA TRADE",
        "LLAMENTOL",
        "LOBSTER FILMS",
        "LOBSTER",
        "LOGON",
        "LORBER FILMS",
        "LORBER",
        "LOS BANDITOS FILMS",
        "LOS BANDITOS",
        "LOUD & PROUD RECORDS",
        "LOUD AND PROUD RECORDS",
        "LOUD & PROUD",
        "LOUD AND PROUD",
        "LSO LIVE",
        "LUCASFILM",
        "LUCKY RED",
        "LUMIÈRE HOME ENTERTAINMENT",
        "LUMIERE HOME ENTERTAINMENT",
        "LUMIERE ENTERTAINMENT",
        "LUMIERE HOME",
        "LUMIERE",
        "M6 VIDEO",
        "M6",
        "MAD DIMENSION",
        "MADMAN ENTERTAINMENT",
        "MADMAN",
        "MAGIC BOX",
        "MAGIC PLAY",
        "MAGNA HOME ENTERTAINMENT",
        "MAGNA ENTERTAINMENT",
        "MAGNA HOME",
        "MAGNA",
        "MAGNOLIA PICTURES",
        "MAGNOLIA",
        "MAIDEN JAPAN",
        "MAIDEN",
        "MAJENG MEDIA",
        "MAJENG",
        "MAJESTIC HOME ENTERTAINMENT",
        "MAJESTIC ENTERTAINMENT",
        "MAJESTIC HOME",
        "MAJESTIC",
        "MANGA HOME ENTERTAINMENT",
        "MANGA ENTERTAINMENT",
        "MANGA HOME",
        "MANGA",
        "MANTA LAB",
        "MAPLE STUDIOS",
        "MAPLE",
        "MARCO POLO PRODUCTION",
        "MARCO POLO",
        "MARIINSKY",
        "MARVEL STUDIOS",
        "MARVEL",
        "MASCOT RECORDS",
        "MASCOT",
        "MASSACRE VIDEO",
        "MASSACRE",
        "MATCHBOX",
        "MATRIX D",
        "MAXAM",
        "MAYA HOME ENTERTAINMENT",
        "MAYA ENTERTAINMENT",
        "MAYA HOME",
        "MAYAT",
        "MDG",
        "MEDIA BLASTERS",
        "MEDIA FACTORY",
        "MEDIA TARGET DISTRIBUTION",
        "MEDIA TARGET",
        "MEDIAINVISION",
        "MEDIATOON",
        "MEDIATRES ESTUDIO",
        "MEDIATRES STUDIO",
        "MEDIATRES",
        "MEDICI ARTS",
        "MEDICI CLASSICS",
        "MEDIUMRARE ENTERTAINMENT",
        "MEDIUMRARE",
        "MEDUSA",
        "MEGASTAR",
        "MEI AH",
        "MELI MÉDIAS",
        "MELI MEDIAS",
        "MEMENTO FILMS",
        "MEMENTO",
        "MENEMSHA FILMS",
        "MENEMSHA",
        "MERCURY",
        "MERCURY STUDIOS",
        "MERGE SOFT PRODUCTIONS",
        "MERGE PRODUCTIONS",
        "MERGE SOFT",
        "MERGE",
        "METAL BLADE RECORDS",
        "METAL BLADE",
        "METEOR",
        "METRO-GOLDWYN-MAYER",
        "METRO GOLDWYN MAYER",
        "METROGOLDWYNMAYER",
        "METRODOME VIDEO",
        "METRODOME",
        "METROPOLITAN",
        "MFA+",
        "MFA",
        "MIG FILMGROUP",
        "MIG",
        "MILESTONE",
        "MILL CREEK ENTERTAINMENT",
        "MILL CREEK",
        "MILLENNIUM MEDIA",
        "MILLENNIUM",
        "MIRAGE ENTERTAINMENT",
        "MIRAGE",
        "MIRAMAX",
        "MISTERIYA ZVUKA",
        "MK2",
        "MODE RECORDS",
        "MODE",
        "MOMENTUM PICTURES",
        "MONDO HOME ENTERTAINMENT",
        "MONDO ENTERTAINMENT",
        "MONDO HOME",
        "MONDO MACABRO",
        "MONGREL MEDIA",
        "MONOLIT",
        "MONOLITH VIDEO",
        "MONOLITH",
        "MONSTER PICTURES",
        "MONSTER",
        "MONTEREY VIDEO",
        "MONTEREY",
        "MONUMENT RELEASING",
        "MONUMENT",
        "MORNINGSTAR",
        "MORNING STAR",
        "MOSERBAER",
        "MOVIEMAX",
        "MOVINSIDE",
        "MPI MEDIA GROUP",
        "MPI MEDIA",
        "MPI",
        "MR. BONGO FILMS",
        "MR BONGO FILMS",
        "MR BONGO",
        "MRG (MERIDIAN)",
        "MRG MERIDIAN",
        "MRG",
        "MERIDIAN",
        "MUBI",
        "MUG SHOT PRODUCTIONS",
        "MUG SHOT",
        "MULTIMUSIC",
        "MULTI-MUSIC",
        "MULTI MUSIC",
        "MUSE",
        "MUSIC BOX FILMS",
        "MUSIC BOX",
        "MUSICBOX",
        "MUSIC BROKERS",
        "MUSIC THEORIES",
        "MUSIC VIDEO DISTRIBUTORS",
        "MUSIC VIDEO",
        "MUSTANG ENTERTAINMENT",
        "MUSTANG",
        "MVD VISUAL",
        "MVD",
        "MVD/VSC",
        "MVL",
        "MVM ENTERTAINMENT",
        "MVM",
        "MYNDFORM",
        "MYSTIC NIGHT PICTURES",
        "MYSTIC NIGHT",
        "NAMELESS MEDIA",
        "NAMELESS",
        "NAPALM RECORDS",
        "NAPALM",
        "NATIONAL ENTERTAINMENT MEDIA",
        "NATIONAL ENTERTAINMENT",
        "NATIONAL MEDIA",
        "NATIONAL FILM ARCHIVE",
        "NATIONAL ARCHIVE",
        "NATIONAL FILM",
        "NATIONAL GEOGRAPHIC",
        "NAT GEO TV",
        "NAT GEO",
        "NGO",
        "NAXOS",
        "NBCUNIVERSAL ENTERTAINMENT JAPAN",
        "NBC UNIVERSAL ENTERTAINMENT JAPAN",
        "NBCUNIVERSAL JAPAN",
        "NBC UNIVERSAL JAPAN",
        "NBC JAPAN",
        "NBO ENTERTAINMENT",
        "NBO",
        "NEOS",
        "NETFLIX",
        "NETWORK",
        "NEW BLOOD",
        "NEW DISC",
        "NEW KSM",
        "NEW LINE CINEMA",
        "NEW LINE",
        "NEW MOVIE TRADING CO. LTD",
        "NEW MOVIE TRADING CO LTD",
        "NEW MOVIE TRADING CO",
        "NEW MOVIE TRADING",
        "NEW WAVE FILMS",
        "NEW WAVE",
        "NFI",
        "NHK",
        "NIPPONART",
        "NIS AMERICA",
        "NJUTAFILMS",
        "NOBLE ENTERTAINMENT",
        "NOBLE",
        "NORDISK FILM",
        "NORDISK",
        "NORSK FILM",
        "NORSK",
        "NORTH AMERICAN MOTION PICTURES",
        "NOS AUDIOVISUAIS",
        "NOTORIOUS PICTURES",
        "NOTORIOUS",
        "NOVA MEDIA",
        "NOVA",
        "NOVA SALES AND DISTRIBUTION",
        "NOVA SALES & DISTRIBUTION",
        "NSM",
        "NSM RECORDS",
        "NUCLEAR BLAST",
        "NUCLEUS FILMS",
        "NUCLEUS",
        "OBERLIN MUSIC",
        "OBERLIN",
        "OBRAS-PRIMAS DO CINEMA",
        "OBRAS PRIMAS DO CINEMA",
        "OBRASPRIMAS DO CINEMA",
        "OBRAS-PRIMAS CINEMA",
        "OBRAS PRIMAS CINEMA",
        "OBRASPRIMAS CINEMA",
        "OBRAS-PRIMAS",
        "OBRAS PRIMAS",
        "OBRASPRIMAS",
        "ODEON",
        "OFDB FILMWORKS",
        "OFDB",
        "OLIVE FILMS",
        "OLIVE",
        "ONDINE",
        "ONSCREEN FILMS",
        "ONSCREEN",
        "OPENING DISTRIBUTION",
        "OPERA AUSTRALIA",
        "OPTIMUM HOME ENTERTAINMENT",
        "OPTIMUM ENTERTAINMENT",
        "OPTIMUM HOME",
        "OPTIMUM",
        "OPUS ARTE",
        "ORANGE STUDIO",
        "ORANGE",
        "ORLANDO EASTWOOD FILMS",
        "ORLANDO FILMS",
        "ORLANDO EASTWOOD",
        "ORLANDO",
        "ORUSTAK PICTURES",
        "ORUSTAK",
        "OSCILLOSCOPE PICTURES",
        "OSCILLOSCOPE",
        "OUTPLAY",
        "PALISADES TARTAN",
        "PAN VISION",
        "PANVISION",
        "PANAMINT CINEMA",
        "PANAMINT",
        "PANDASTORM ENTERTAINMENT",
        "PANDA STORM ENTERTAINMENT",
        "PANDASTORM",
        "PANDA STORM",
        "PANDORA FILM",
        "PANDORA",
        "PANEGYRIC",
        "PANORAMA",
        "PARADE DECK FILMS",
        "PARADE DECK",
        "PARADISE",
        "PARADISO FILMS",
        "PARADOX",
        "PARAMOUNT PICTURES",
        "PARAMOUNT",
        "PARIS FILMES",
        "PARIS FILMS",
        "PARIS",
        "PARK CIRCUS",
        "PARLOPHONE",
        "PASSION RIVER",
        "PATHE DISTRIBUTION",
        "PATHE",
        "PBS",
        "PEACE ARCH TRINITY",
        "PECCADILLO PICTURES",
        "PEPPERMINT",
        "PHASE 4 FILMS",
        "PHASE 4",
        "PHILHARMONIA BAROQUE",
        "PICTURE HOUSE ENTERTAINMENT",
        "PICTURE ENTERTAINMENT",
        "PICTURE HOUSE",
        "PICTURE",
        "PIDAX",
        "PINK FLOYD RECORDS",
        "PINK FLOYD",
        "PINNACLE FILMS",
        "PINNACLE",
        "PLAIN",
        "PLATFORM ENTERTAINMENT LIMITED",
        "PLATFORM ENTERTAINMENT LTD",
        "PLATFORM ENTERTAINMENT LTD.",
        "PLATFORM ENTERTAINMENT",
        "PLATFORM",
        "PLAYARTE",
        "PLG UK CLASSICS",
        "PLG UK",
        "PLG",
        "POLYBAND & TOPPIC VIDEO/WVG",
        "POLYBAND AND TOPPIC VIDEO/WVG",
        "POLYBAND & TOPPIC VIDEO WVG",
        "POLYBAND & TOPPIC VIDEO AND WVG",
        "POLYBAND & TOPPIC VIDEO & WVG",
        "POLYBAND AND TOPPIC VIDEO WVG",
        "POLYBAND AND TOPPIC VIDEO AND WVG",
        "POLYBAND AND TOPPIC VIDEO & WVG",
        "POLYBAND & TOPPIC VIDEO",
        "POLYBAND AND TOPPIC VIDEO",
        "POLYBAND & TOPPIC",
        "POLYBAND AND TOPPIC",
        "POLYBAND",
        "WVG",
        "POLYDOR",
        "PONY",
        "PONY CANYON",
        "POTEMKINE",
        "POWERHOUSE FILMS",
        "POWERHOUSE",
        "POWERSTATIOM",
        "PRIDE & JOY",
        "PRIDE AND JOY",
        "PRINZ MEDIA",
        "PRINZ",
        "PRIS AUDIOVISUAIS",
        "PRO VIDEO",
        "PRO-VIDEO",
        "PRO-MOTION",
        "PRO MOTION",
        "PROD. JRB",
        "PROD JRB",
        "PRODISC",
        "PROKINO",
        "PROVOGUE RECORDS",
        "PROVOGUE",
        "PROWARE",
        "PULP VIDEO",
        "PULP",
        "PULSE VIDEO",
        "PULSE",
        "PURE AUDIO RECORDINGS",
        "PURE AUDIO",
        "PURE FLIX ENTERTAINMENT",
        "PURE FLIX",
        "PURE ENTERTAINMENT",
        "PYRAMIDE VIDEO",
        "PYRAMIDE",
        "QUALITY FILMS",
        "QUALITY",
        "QUARTO VALLEY RECORDS",
        "QUARTO VALLEY",
        "QUESTAR",
        "R SQUARED FILMS",
        "R SQUARED",
        "RAPID EYE MOVIES",
        "RAPID EYE",
        "RARO VIDEO",
        "RARO",
        "RAROVIDEO U.S.",
        "RAROVIDEO US",
        "RARO VIDEO US",
        "RARO VIDEO U.S.",
        "RARO U.S.",
        "RARO US",
        "RAVEN BANNER RELEASING",
        "RAVEN BANNER",
        "RAVEN",
        "RAZOR DIGITAL ENTERTAINMENT",
        "RAZOR DIGITAL",
        "RCA",
        "RCO LIVE",
        "RCO",
        "RCV",
        "REAL GONE MUSIC",
        "REAL GONE",
        "REANIMEDIA",
        "REANI MEDIA",
        "REDEMPTION",
        "REEL",
        "RELIANCE HOME VIDEO & GAMES",
        "RELIANCE HOME VIDEO AND GAMES",
        "RELIANCE HOME VIDEO",
        "RELIANCE VIDEO",
        "RELIANCE HOME",
        "RELIANCE",
        "REM CULTURE",
        "REMAIN IN LIGHT",
        "REPRISE",
        "RESEN",
        "RETROMEDIA",
        "REVELATION FILMS LTD.",
        "REVELATION FILMS LTD",
        "REVELATION FILMS",
        "REVELATION LTD.",
        "REVELATION LTD",
        "REVELATION",
        "REVOLVER ENTERTAINMENT",
        "REVOLVER",
        "RHINO MUSIC",
        "RHINO",
        "RHV",
        "RIGHT STUF",
        "RIMINI EDITIONS",
        "RISING SUN MEDIA",
        "RLJ ENTERTAINMENT",
        "RLJ",
        "ROADRUNNER RECORDS",
        "ROADSHOW ENTERTAINMENT",
        "ROADSHOW",
        "RONE",
        "RONIN FLIX",
        "ROTANA HOME ENTERTAINMENT",
        "ROTANA ENTERTAINMENT",
        "ROTANA HOME",
        "ROTANA",
        "ROUGH TRADE",
        "ROUNDER",
        "SAFFRON HILL FILMS",
        "SAFFRON HILL",
        "SAFFRON",
        "SAMUEL GOLDWYN FILMS",
        "SAMUEL GOLDWYN",
        "SAN FRANCISCO SYMPHONY",
        "SANDREW METRONOME",
        "SAPHRANE",
        "SAVOR",
        "SCANBOX ENTERTAINMENT",
        "SCANBOX",
        "SCENIC LABS",
        "SCHRÖDERMEDIA",
        "SCHRODERMEDIA",
        "SCHRODER MEDIA",
        "SCORPION RELEASING",
        "SCORPION",
        "SCREAM TEAM RELEASING",
        "SCREAM TEAM",
        "SCREEN MEDIA",
        "SCREEN",
        "SCREENBOUND PICTURES",
        "SCREENBOUND",
        "SCREENWAVE MEDIA",
        "SCREENWAVE",
        "SECOND RUN",
        "SECOND SIGHT",
        "SEEDSMAN GROUP",
        "SELECT VIDEO",
        "SELECTA VISION",
        "SENATOR",
        "SENTAI FILMWORKS",
        "SENTAI",
        "SEVEN7",
        "SEVERIN FILMS",
        "SEVERIN",
        "SEVILLE",
        "SEYONS ENTERTAINMENT",
        "SEYONS",
        "SF STUDIOS",
        "SGL ENTERTAINMENT",
        "SGL",
        "SHAMELESS",
        "SHAMROCK MEDIA",
        "SHAMROCK",
        "SHANGHAI EPIC MUSIC ENTERTAINMENT",
        "SHANGHAI EPIC ENTERTAINMENT",
        "SHANGHAI EPIC MUSIC",
        "SHANGHAI MUSIC ENTERTAINMENT",
        "SHANGHAI ENTERTAINMENT",
        "SHANGHAI MUSIC",
        "SHANGHAI",
        "SHEMAROO",
        "SHOCHIKU",
        "SHOCK",
        "SHOGAKU KAN",
        "SHOUT FACTORY",
        "SHOUT! FACTORY",
        "SHOUT",
        "SHOUT!",
        "SHOWBOX",
        "SHOWTIME ENTERTAINMENT",
        "SHOWTIME",
        "SHRIEK SHOW",
        "SHUDDER",
        "SIDONIS",
        "SIDONIS CALYSTA",
        "SIGNAL ONE ENTERTAINMENT",
        "SIGNAL ONE",
        "SIGNATURE ENTERTAINMENT",
        "SIGNATURE",
        "SILVER VISION",
        "SINISTER FILM",
        "SINISTER",
        "SIREN VISUAL ENTERTAINMENT",
        "SIREN VISUAL",
        "SIREN ENTERTAINMENT",
        "SIREN",
        "SKANI",
        "SKY DIGI",
        "SLASHER // VIDEO",
        "SLASHER / VIDEO",
        "SLASHER VIDEO",
        "SLASHER",
        "SLOVAK FILM INSTITUTE",
        "SLOVAK FILM",
        "SFI",
        "SM LIFE DESIGN GROUP",
        "SMOOTH PICTURES",
        "SMOOTH",
        "SNAPPER MUSIC",
        "SNAPPER",
        "SODA PICTURES",
        "SODA",
        "SONO LUMINUS",
        "SONY MUSIC",
        "SONY PICTURES",
        "SONY",
        "SONY PICTURES CLASSICS",
        "SONY CLASSICS",
        "SOUL MEDIA",
        "SOUL",
        "SOULFOOD MUSIC DISTRIBUTION",
        "SOULFOOD DISTRIBUTION",
        "SOULFOOD MUSIC",
        "SOULFOOD",
        "SOYUZ",
        "SPECTRUM",
        "SPENTZOS FILM",
        "SPENTZOS",
        "SPIRIT ENTERTAINMENT",
        "SPIRIT",
        "SPIRIT MEDIA GMBH",
        "SPIRIT MEDIA",
        "SPLENDID ENTERTAINMENT",
        "SPLENDID FILM",
        "SPO",
        "SQUARE ENIX",
        "SRI BALAJI VIDEO",
        "SRI BALAJI",
        "SRI",
        "SRI VIDEO",
        "SRS CINEMA",
        "SRS",
        "SSO RECORDINGS",
        "SSO",
        "ST2 MUSIC",
        "ST2",
        "STAR MEDIA ENTERTAINMENT",
        "STAR ENTERTAINMENT",
        "STAR MEDIA",
        "STAR",
        "STARLIGHT",
        "STARZ / ANCHOR BAY",
        "STARZ ANCHOR BAY",
        "STARZ",
        "ANCHOR BAY",
        "STER KINEKOR",
        "STERLING ENTERTAINMENT",
        "STERLING",
        "STINGRAY",
        "STOCKFISCH RECORDS",
        "STOCKFISCH",
        "STRAND RELEASING",
        "STRAND",
        "STUDIO 4K",
        "STUDIO CANAL",
        "STUDIO GHIBLI",
        "GHIBLI",
        "STUDIO HAMBURG ENTERPRISES",
        "HAMBURG ENTERPRISES",
        "STUDIO HAMBURG",
        "HAMBURG",
        "STUDIO S",
        "SUBKULTUR ENTERTAINMENT",
        "SUBKULTUR",
        "SUEVIA FILMS",
        "SUEVIA",
        "SUMMIT ENTERTAINMENT",
        "SUMMIT",
        "SUNFILM ENTERTAINMENT",
        "SUNFILM",
        "SURROUND RECORDS",
        "SURROUND",
        "SVENSK FILMINDUSTRI",
        "SVENSK",
        "SWEN FILMES",
        "SWEN FILMS",
        "SWEN",
        "SYNAPSE FILMS",
        "SYNAPSE",
        "SYNDICADO",
        "SYNERGETIC",
        "T- SERIES",
        "T-SERIES",
        "T SERIES",
        "TSERIES",
        "T.V.P.",
        "TVP",
        "TACET RECORDS",
        "TACET",
        "TAI SENG",
        "TAI SHENG",
        "TAKEONE",
        "TAKESHOBO",
        "TAMASA DIFFUSION",
        "TC ENTERTAINMENT",
        "TC",
        "TDK",
        "TEAM MARKETING",
        "TEATRO REAL",
        "TEMA DISTRIBUCIONES",
        "TEMPE DIGITAL",
        "TF1 VIDÉO",
        "TF1 VIDEO",
        "TF1",
        "THE BLU",
        "BLU",
        "THE ECSTASY OF FILMS",
        "THE FILM DETECTIVE",
        "FILM DETECTIVE",
        "THE JOKERS",
        "JOKERS",
        "THE ON",
        "ON",
        "THIMFILM",
        "THIM FILM",
        "THIM",
        "THIRD WINDOW FILMS",
        "THIRD WINDOW",
        "3RD WINDOW FILMS",
        "3RD WINDOW",
        "THUNDERBEAN ANIMATION",
        "THUNDERBEAN",
        "THUNDERBIRD RELEASING",
        "THUNDERBIRD",
        "TIBERIUS FILM",
        "TIME LIFE",
        "TIMELESS MEDIA GROUP",
        "TIMELESS MEDIA",
        "TIMELESS GROUP",
        "TIMELESS",
        "TLA RELEASING",
        "TLA",
        "TOBIS FILM",
        "TOBIS",
        "TOEI",
        "TOHO",
        "TOKYO SHOCK",
        "TOKYO",
        "TONPOOL MEDIEN GMBH",
        "TONPOOL MEDIEN",
        "TOPICS ENTERTAINMENT",
        "TOPICS",
        "TOUCHSTONE PICTURES",
        "TOUCHSTONE",
        "TRANSMISSION FILMS",
        "TRANSMISSION",
        "TRAVEL VIDEO STORE",
        "TRIART",
        "TRIGON FILM",
        "TRIGON",
        "TRINITY HOME ENTERTAINMENT",
        "TRINITY ENTERTAINMENT",
        "TRINITY HOME",
        "TRINITY",
        "TRIPICTURES",
        "TRI-PICTURES",
        "TRI PICTURES",
        "TROMA",
        "TURBINE MEDIEN",
        "TURTLE RECORDS",
        "TURTLE",
        "TVA FILMS",
        "TVA",
        "TWILIGHT TIME",
        "TWILIGHT",
        "TT",
        "TWIN CO., LTD.",
        "TWIN CO, LTD.",
        "TWIN CO., LTD",
        "TWIN CO, LTD",
        "TWIN CO LTD",
        "TWIN LTD",
        "TWIN CO.",
        "TWIN CO",
        "TWIN",
        "UCA",
        "UDR",
        "UEK",
        "UFA/DVD",
        "UFA DVD",
        "UFADVD",
        "UGC PH",
        "ULTIMATE3DHEAVEN",
        "ULTRA",
        "UMBRELLA ENTERTAINMENT",
        "UMBRELLA",
        "UMC",
        "UNCORK'D ENTERTAINMENT",
        "UNCORKD ENTERTAINMENT",
        "UNCORK D ENTERTAINMENT",
        "UNCORK'D",
        "UNCORK D",
        "UNCORKD",
        "UNEARTHED FILMS",
        "UNEARTHED",
        "UNI DISC",
        "UNIMUNDOS",
        "UNITEL",
        "UNIVERSAL MUSIC",
        "UNIVERSAL SONY PICTURES HOME ENTERTAINMENT",
        "UNIVERSAL SONY PICTURES ENTERTAINMENT",
        "UNIVERSAL SONY PICTURES HOME",
        "UNIVERSAL SONY PICTURES",
        "UNIVERSAL HOME ENTERTAINMENT",
        "UNIVERSAL ENTERTAINMENT",
        "UNIVERSAL HOME",
        "UNIVERSAL STUDIOS",
        "UNIVERSAL",
        "UNIVERSE LASER & VIDEO CO.",
        "UNIVERSE LASER AND VIDEO CO.",
        "UNIVERSE LASER & VIDEO CO",
        "UNIVERSE LASER AND VIDEO CO",
        "UNIVERSE LASER CO.",
        "UNIVERSE LASER CO",
        "UNIVERSE LASER",
        "UNIVERSUM FILM",
        "UNIVERSUM",
        "UTV",
        "VAP",
        "VCI",
        "VENDETTA FILMS",
        "VENDETTA",
        "VERSÁTIL HOME VIDEO",
        "VERSÁTIL VIDEO",
        "VERSÁTIL HOME",
        "VERSÁTIL",
        "VERSATIL HOME VIDEO",
        "VERSATIL VIDEO",
        "VERSATIL HOME",
        "VERSATIL",
        "VERTICAL ENTERTAINMENT",
        "VERTICAL",
        "VÉRTICE 360º",
        "VÉRTICE 360",
        "VERTICE 360o",
        "VERTICE 360",
        "VERTIGO BERLIN",
        "VÉRTIGO FILMS",
        "VÉRTIGO",
        "VERTIGO FILMS",
        "VERTIGO",
        "VERVE PICTURES",
        "VIA VISION ENTERTAINMENT",
        "VIA VISION",
        "VICOL ENTERTAINMENT",
        "VICOL",
        "VICOM",
        "VICTOR ENTERTAINMENT",
        "VICTOR",
        "VIDEA CDE",
        "VIDEO FILM EXPRESS",
        "VIDEO FILM",
        "VIDEO EXPRESS",
        "VIDEO MUSIC, INC.",
        "VIDEO MUSIC, INC",
        "VIDEO MUSIC INC.",
        "VIDEO MUSIC INC",
        "VIDEO MUSIC",
        "VIDEO SERVICE CORP.",
        "VIDEO SERVICE CORP",
        "VIDEO SERVICE",
        "VIDEO TRAVEL",
        "VIDEOMAX",
        "VIDEO MAX",
        "VII PILLARS ENTERTAINMENT",
        "VII PILLARS",
        "VILLAGE FILMS",
        "VINEGAR SYNDROME",
        "VINEGAR",
        "VS",
        "VINNY MOVIES",
        "VINNY",
        "VIRGIL FILMS & ENTERTAINMENT",
        "VIRGIL FILMS AND ENTERTAINMENT",
        "VIRGIL ENTERTAINMENT",
        "VIRGIL FILMS",
        "VIRGIL",
        "VIRGIN RECORDS",
        "VIRGIN",
        "VISION FILMS",
        "VISION",
        "VISUAL ENTERTAINMENT GROUP",
        "VISUAL GROUP",
        "VISUAL ENTERTAINMENT",
        "VISUAL",
        "VIVENDI VISUAL ENTERTAINMENT",
        "VIVENDI VISUAL",
        "VIVENDI",
        "VIZ PICTURES",
        "VIZ",
        "VLMEDIA",
        "VL MEDIA",
        "VL",
        "VOLGA",
        "VVS FILMS",
        "VVS",
        "VZ HANDELS GMBH",
        "VZ HANDELS",
        "WARD RECORDS",
        "WARD",
        "WARNER BROS.",
        "WARNER BROS",
        "WARNER ARCHIVE",
        "WARNER ARCHIVE COLLECTION",
        "WAC",
        "WARNER",
        "WARNER MUSIC",
        "WEA",
        "WEINSTEIN COMPANY",
        "WEINSTEIN",
        "WELL GO USA",
        "WELL GO",
        "WELTKINO FILMVERLEIH",
        "WEST VIDEO",
        "WEST",
        "WHITE PEARL MOVIES",
        "WHITE PEARL",
        "WICKED-VISION MEDIA",
        "WICKED VISION MEDIA",
        "WICKEDVISION MEDIA",
        "WICKED-VISION",
        "WICKED VISION",
        "WICKEDVISION",
        "WIENERWORLD",
        "WILD BUNCH",
        "WILD EYE RELEASING",
        "WILD EYE",
        "WILD SIDE VIDEO",
        "WILD SIDE",
        "WME",
        "WOLFE VIDEO",
        "WOLFE",
        "WORD ON FIRE",
        "WORKS FILM GROUP",
        "WORLD WRESTLING",
        "WVG MEDIEN",
        "WWE STUDIOS",
        "WWE",
        "X RATED KULT",
        "X-RATED KULT",
        "X RATED CULT",
        "X-RATED CULT",
        "X RATED",
        "X-RATED",
        "XCESS",
        "XLRATOR",
        "XT VIDEO",
        "XT",
        "YAMATO VIDEO",
        "YAMATO",
        "YASH RAJ FILMS",
        "YASH RAJS",
        "ZEITGEIST FILMS",
        "ZEITGEIST",
        "ZENITH PICTURES",
        "ZENITH",
        "ZIMA",
        "ZYLO",
        "ZYX MUSIC",
        "ZYX",
        "MASTERS OF CINEMA",
        "MOC",
    ]
    distributor_out = ""
    if distributor_in is not None and distributor_in not in ["None", ""]:
        for each in distributor_list:
            if distributor_in.upper() == each:
                distributor_out = each
    return distributor_out


async def get_service(
    video: Optional[str] = None, tag: Optional[str] = None, audio: Optional[str] = None, guess_title: Optional[str] = None, get_services_only: bool = False
) -> Union[dict[str, str], tuple[str, str]]:
    services = {
        '9NOW': '9NOW', '9Now': '9NOW', 'ADN': 'ADN', 'Animation Digital Network': 'ADN', 'AE': 'AE', 'A&E': 'AE', 'AJAZ': 'AJAZ', 'Al Jazeera English': 'AJAZ',
        'ALL4': 'ALL4', 'Channel 4': 'ALL4', 'AMBC': 'AMBC', 'ABC': 'AMBC', 'AMC': 'AMC', 'AMZN': 'AMZN',
        'Amazon Prime': 'AMZN', 'ANLB': 'ANLB', 'AnimeLab': 'ANLB', 'ANPL': 'ANPL', 'Animal Planet': 'ANPL',
        'AOL': 'AOL', 'ARD': 'ARD', 'AS': 'AS', 'Adult Swim': 'AS', 'ATK': 'ATK', "America's Test Kitchen": 'ATK', 'ATV': 'ATV', 'Apple TV': 'ATV',
        'ATVP': 'ATVP', 'Apple TV+': 'ATVP', 'AUBC': 'AUBC', 'ABC Australia': 'AUBC', 'BCORE': 'BCORE', 'Bilibili': 'BILI', 'BILI': 'BILI', 'BKPL': 'BKPL',
        'Blackpills': 'BKPL', 'BluTV': 'BLU', 'Binge': 'BNGE', 'BOOM': 'BOOM', 'Boomerang': 'BOOM', 'Brasil Paralelo': 'BP', 'BP': 'BP', 'BRAV': 'BRAV',
        'BravoTV': 'BRAV', 'CBC': 'CBC', 'CBS': 'CBS', 'CC': 'CC', 'Comedy Central': 'CC', 'CCGC': 'CCGC',
        'Comedians in Cars Getting Coffee': 'CCGC', 'CHGD': 'CHGD', 'CHRGD': 'CHGD', 'CMAX': 'CMAX', 'Cinemax': 'CMAX',
        'CMOR': 'CMOR', 'CMT': 'CMT', 'Country Music Television': 'CMT', 'CN': 'CN', 'Cartoon Network': 'CN', 'CNBC': 'CNBC',
        'CNLP': 'CNLP', 'Canal+': 'CNLP', 'CNGO': 'CNGO', 'Cinego': 'CNGO', 'COOK': 'COOK', 'CORE': 'CORE', 'CR': 'CR',
        'Crunchy Roll': 'CR', 'Crave': 'CRAV', 'CRAV': 'CRAV', 'CRIT': 'CRIT', 'Criterion': 'CRIT', 'Chorki': 'CRKI', 'CRKI': 'CRKI', 'CRKL': 'CRKL', 'Crackle': 'CRKL',
        'CSPN': 'CSPN', 'CSpan': 'CSPN', 'CTHP': 'CTHP', 'CTV': 'CTV', 'CUR': 'CUR', 'CuriosityStream': 'CUR', 'CW': 'CW', 'The CW': 'CW',
        'CWS': 'CWS', 'CWSeed': 'CWS', 'DAZN': 'DAZN', 'DCU': 'DCU', 'DC Universe': 'DCU', 'DDY': 'DDY',
        'Digiturk Diledigin Yerde': 'DDY', 'DEST': 'DEST', 'DramaFever': 'DF', 'DHF': 'DHF', 'Deadhouse Films': 'DHF',
        'DISC': 'DISC', 'Discovery': 'DISC', 'DIY': 'DIY', 'DIY Network': 'DIY', 'DOCC': 'DOCC', 'Doc Club': 'DOCC', 'DOCPLAY': 'DOCPLAY',
        'DPLY': 'DPLY', 'DPlay': 'DPLY', 'DRPO': 'DRPO', 'Discovery Plus': 'DSCP', 'DSKI': 'DSKI', 'Daisuki': 'DSKI',
        'DSNP': 'DSNP', 'Disney+': 'DSNP', 'DSNY': 'DSNY', 'Disney': 'DSNY', 'DTV': 'DTV', 'EPIX': 'EPIX', 'ePix': 'EPIX',
        'ESPN': 'ESPN', 'ESQ': 'ESQ', 'Esquire': 'ESQ', 'ETTV': 'ETTV', 'El Trece': 'ETTV', 'ETV': 'ETV', 'E!': 'ETV',
        'FAM': 'FAM', 'Fandor': 'FANDOR', 'Facebook Watch': 'FBWatch', 'FJR': 'FJR', 'Family Jr': 'FJR', 'FMIO': 'FMIO',
        'Filmio': 'FMIO', 'FOOD': 'FOOD', 'Food Network': 'FOOD', 'FOX': 'FOX', 'Fox': 'FOX', 'Fox Premium': 'FOXP',
        'UFC Fight Pass': 'FP', 'FPT': 'FPT', 'FREE': 'FREE', 'Freeform': 'FREE', 'FTV': 'FTV', 'FUNI': 'FUNI', 'FUNi': 'FUNI',
        'Foxtel': 'FXTL', 'FYI': 'FYI', 'FYI Network': 'FYI', 'GC': 'GC', 'NHL GameCenter': 'GC', 'GLBL': 'GLBL',
        'Global': 'GLBL', 'GLBO': 'GLBO', 'Globoplay': 'GLBO', 'GLOB': 'GLOB', 'GloboSat Play': 'GLOB', 'GO90': 'GO90', 'GagaOOLala': 'Gaga', 'HBO': 'HBO',
        'HBO Go': 'HBO', 'HGTV': 'HGTV', 'HIDI': 'HIDI', 'HiDive': 'HIDI', 'HIST': 'HIST', 'History': 'HIST', 'HLMK': 'HLMK', 'Hallmark': 'HLMK',
        'HMAX': 'HMAX', 'HBO Max': 'HMAX', 'HBOMAX': 'HMAX', 'HS': 'HTSR', 'HTSR': 'HTSR', 'HSTR': 'Hotstar', 'HULU': 'HULU', 'Hulu': 'HULU',
        'hoichoi': 'HoiChoi', 'ID': 'ID', 'Investigation Discovery': 'ID', 'IFC': 'IFC', 'iflix': 'IFX',
        'National Audiovisual Institute': 'INA', 'ITV': 'ITV', 'JOYN': 'JOYN', 'KAYO': 'KAYO', 'KNOW': 'KNOW', 'Knowledge Network': 'KNOW',
        'KNPY': 'KNPY', 'Kanopy': 'KNPY', 'Kocowa+': 'KCW', 'Kocowa': 'KCW', 'KCW': 'KCW', 'LIFE': 'LIFE', 'Lifetime': 'LIFE', 'LN': 'LN', 'MA': 'MA', 'Looke': 'LOOKE', 'LOOKE': 'LOOKE', 'Movies Anywhere': 'MA',
        'MAX': 'MAX', 'MBC': 'MBC', 'MNBC': 'MNBC', 'MSNBC': 'MNBC', 'MTOD': 'MTOD', 'Motor Trend OnDemand': 'MTOD', 'MTV': 'MTV',
        'MUBI': 'MUBI', 'NATG': 'NATG', 'National Geographic': 'NATG', 'NBA': 'NBA', 'NBA TV': 'NBA', 'NBC': 'NBC', 'NF': 'NF',
        'NBLA': 'NBLA', 'Nebula': 'NBLA', 'Netflix': 'NF', 'National Film Board': 'NFB', 'NFL': 'NFL', 'NFLN': 'NFLN', 'NFL Now': 'NFLN', 'NICK': 'NICK',
        'Nickelodeon': 'NICK', 'NOW': 'NOW', 'NOWTV': 'NOW', 'NRK': 'NRK', 'Norsk Rikskringkasting': 'NRK', 'OnDemandKorea': 'ODK', 'Opto': 'OPTO',
        'ORF': 'ORF', 'ORF ON': 'ORF', 'Oprah Winfrey Network': 'OWN', 'PA': 'PA', 'PBS': 'PBS', 'PBSK': 'PBSK', 'PBS Kids': 'PBSK',
        'PCOK': 'PCOK', 'Peacock': 'PCOK', 'PLAY': 'PLAY', 'PLTV': 'PLTV', 'Pluto TV': 'PLTV', 'PLUZ': 'PLUZ', 'Pluzz': 'PLUZ', 'PMNP': 'PMNP', 'PMNT': 'PMNT',
        'PMTP': 'PMTP', 'POGO': 'POGO', 'PokerGO': 'POGO', 'PSN': 'PSN', 'Playstation Network': 'PSN', 'PUHU': 'PUHU', 'QIBI': 'QIBI',
        'RED': 'RED', 'YouTube Red': 'RED', 'RKTN': 'RKTN', 'Rakuten TV': 'RKTN', 'The Roku Channel': 'ROKU', 'RNET': 'RNET',
        'OBB Railnet': 'RNET', 'RSTR': 'RSTR', 'RTE': 'RTE', 'RTE One': 'RTE', 'RTLP': 'RTLP', 'RTL+': 'RTLP', 'RUUTU': 'RUUTU',
        'SBS': 'SBS', 'Science Channel': 'SCI', 'SESO': 'SESO', 'SeeSo': 'SESO', 'SHMI': 'SHMI', 'Shomi': 'SHMI', 'SKST': 'SKST',
        'SkyShowtime': 'SKST', 'SHO': 'SHO', 'Showtime': 'SHO', 'SNET': 'SNET', 'Sportsnet': 'SNET', 'Sony': 'SONY', 'SPIK': 'SPIK',
        'Spike': 'SPIK', 'Spike TV': 'SPKE', 'SPRT': 'SPRT', 'Sprout': 'SPRT', 'STAN': 'STAN', 'Stan': 'STAN', 'STARZ': 'STARZ',
        'STRP': 'STRP', 'Star+': 'STRP', 'STZ': 'STZ', 'Starz': 'STZ', 'SVT': 'SVT', 'Sveriges Television': 'SVT', 'SWER': 'SWER',
        'SwearNet': 'SWER', 'SYFY': 'SYFY', 'Syfy': 'SYFY', 'TBS': 'TBS', 'TEN': 'TEN', 'TIMV': 'TIMV', 'TIMvision': 'TIMV',
        'TFOU': 'TFOU', 'TFou': 'TFOU', 'TLC': 'TLC', 'TOU': 'TOU', 'TRVL': 'TRVL', 'TUBI': 'TUBI', 'TubiTV': 'TUBI',
        'TV3': 'TV3', 'TV3 Ireland': 'TV3', 'TV4': 'TV4', 'TV4 Sweeden': 'TV4', 'TVING': 'TVING', 'TVL': 'TVL', 'TV Land': 'TVL',
        'TVNZ': 'TVNZ', 'UFC': 'UFC', 'UKTV': 'UKTV', 'UNIV': 'UNIV', 'Univision': 'UNIV', 'USAN': 'USAN', 'USA Network': 'USAN',
        'VH1': 'VH1', 'VIAP': 'VIAP', 'VICE': 'VICE', 'Viceland': 'VICE', 'Viki': 'VIKI', 'VIMEO': 'VIMEO', 'Vivamax': 'VMAX', 'VMAX': 'VMAX', 'Vivaone': 'VONE', 'VONE': 'VONE', 'VLCT': 'VLCT',
        'Velocity': 'VLCT', 'VMEO': 'VMEO', 'Vimeo': 'VMEO', 'VRV': 'VRV', 'VUDU': 'VUDU', 'WME': 'WME', 'WatchMe': 'WME', 'WNET': 'WNET',
        'W Network': 'WNET', 'WOW Presents Plus': 'WOWP', 'WOWP': 'WOWP', 'WWEN': 'WWEN', 'WWE Network': 'WWEN', 'XBOX': 'XBOX', 'Xbox Video': 'XBOX', 'XUMO': 'XUMO', 'YHOO': 'YHOO', 'Yahoo': 'YHOO',
        'YT': 'YT', 'ZDF': 'ZDF', 'iP': 'iP', 'BBC iPlayer': 'iP', 'iQIYI': 'iQIYI', 'iT': 'iT', 'iTunes': 'iT',
        'MGG': 'MGG', 'Megogo': 'MGG', 'MEGOGO': 'MGG', 'MeGoGo': 'MGG',
        'SWEET': 'SWEET',
        'KS': 'KS', 'Kyivstar': 'KS', 'KyivstarTV': 'KS', 'Kyivstar TV': 'KS', 'kyivstar': 'KS',
        'PKO': 'PKO', 'Planeta Kino Online': 'PKO',
        'TF': 'TF', 'takflix': 'TF', 'Takflix': 'TF'
    }  # fmt: off

    if get_services_only:
        return services

    if video is None:
        return "", ""

    guess_data = guessit_fn(video)
    service: str = str(guess_data.get("streaming_service", ""))

    video_name = re.sub(r"[.()]", " ", video.replace(tag or "", "").replace(guess_title or "", ""))
    if audio and "DTS-HD MA" in audio:
        video_name = video_name.replace("DTS-HD.MA.", "").replace("DTS-HD MA ", "")
    title_guess = guessit_fn(video, {"excludes": ["country", "language"]})
    title_guess_title = str(title_guess.get("title", ""))
    for key, value in services.items():
        if (" " + key + " ") in video_name and key not in title_guess_title or key == service:
            service = value
    service_longname: str = service
    for key, value in services.items():
        if value == service and len(key) > len(service_longname):
            service_longname = key
    if service_longname == "Amazon Prime":
        service_longname = "Amazon"
    return service, service_longname
